### PR TITLE
Add server option

### PR DESCRIPTION
**Pull request by fetzi**
allow use of custom PlantUML server to avoid rewriting the generateSource function

### CODE REVIEW

**Comment by gmunguia** [comment]
Hi! Thanks for your contribution =).

Could you add a test for this case? Simply verifying that the server URL appears properly in the image tag would be enough.

**Comment by fetzi** [comment]
Done, thanks for your quick response!

**Comment by gmunguia** [comment]
Well, that was quick =D.

**Comment by gmunguia** [comment]
Published in v1.3.0

**Pull request merged**
